from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from time import sleep
import pandas as pd

df = pd.DataFrame()

l1 = []

service = Service(executable_path='./chromedriver.exe')
options = webdriver.ChromeOptions()


browser = webdriver.Chrome(service=service, options=options)
#browser.get('https://www.totaltraininfo.com/a.php')
#browser.get('https://www.totaltraininfo.com/a.php?page=1')
#browser.get('https://www.totaltraininfo.com/a.php?page=2')
#browser.get('https://www.totaltraininfo.com/b.php')
#browser.get('https://www.totaltraininfo.com/b.php?page=1')
#browser.get('https://www.totaltraininfo.com/b.php?page=2')
#browser.get('https://www.totaltraininfo.com/b.php?page=3')
#browser.get('https://www.totaltraininfo.com/b.php?page=4')
#browser.get('https://www.totaltraininfo.com/b.php?page=5')
#browser.get('https://www.totaltraininfo.com/c.php')
#browser.get('https://www.totaltraininfo.com/c.php?page=1')
#browser.get('https://www.totaltraininfo.com/d.php')
#browser.get('https://www.totaltraininfo.com/d.php?page=1')
#browser.get('https://www.totaltraininfo.com/d.php?page=2')
#browser.get('https://www.totaltraininfo.com/e.php')
#browser.get('https://www.totaltraininfo.com/f.php')
#browser.get('https://www.totaltraininfo.com/g.php')
#browser.get('https://www.totaltraininfo.com/g.php?page=1')
#browser.get('https://www.totaltraininfo.com/g.php?page=2')
#browser.get('https://www.totaltraininfo.com/h.php')
#browser.get('https://www.totaltraininfo.com/h.php?page=1')
#browser.get('https://www.totaltraininfo.com/i.php')
#browser.get('https://www.totaltraininfo.com/j.php')
#browser.get('https://www.totaltraininfo.com/j.php?page=1')
#browser.get('https://www.totaltraininfo.com/k.php')
#browser.get('https://www.totaltraininfo.com/k.php?page=1')
#browser.get('https://www.totaltraininfo.com/k.php?page=2')
#browser.get('https://www.totaltraininfo.com/k.php?page=3')
#browser.get('https://www.totaltraininfo.com/k.php?page=4')
#browser.get('https://www.totaltraininfo.com/k.php?page=5')
#browser.get('https://www.totaltraininfo.com/l.php')
#browser.get('https://www.totaltraininfo.com/l.php?page=1')
#browser.get('https://www.totaltraininfo.com/m.php')
#browser.get('https://www.totaltraininfo.com/m.php?page=1')
#browser.get('https://www.totaltraininfo.com/m.php?page=2')
#browser.get('https://www.totaltraininfo.com/m.php?page=3')
#browser.get('https://www.totaltraininfo.com/m.php?page=4')
#browser.get('https://www.totaltraininfo.com/n.php')
#browser.get('https://www.totaltraininfo.com/n.php?page=1')
#browser.get('https://www.totaltraininfo.com/n.php?page=2')
#browser.get('https://www.totaltraininfo.com/o.php')
#browser.get('https://www.totaltraininfo.com/p.php')
#browser.get('https://www.totaltraininfo.com/p.php?page=1')
#browser.get('https://www.totaltraininfo.com/p.php?page=2')
#browser.get('https://www.totaltraininfo.com/q.php')
#browser.get('https://www.totaltraininfo.com/r.php')
#browser.get('https://www.totaltraininfo.com/r.php?page=1')
#browser.get('https://www.totaltraininfo.com/s.php')
#browser.get('https://www.totaltraininfo.com/s.php?page=1')
#browser.get('https://www.totaltraininfo.com/s.php?page=2')
#browser.get('https://www.totaltraininfo.com/s.php?page=3')
#browser.get('https://www.totaltraininfo.com/s.php?page=4')
#browser.get('https://www.totaltraininfo.com/t.php')
#browser.get('https://www.totaltraininfo.com/t.php?page=1')
#browser.get('https://www.totaltraininfo.com/t.php?page=2')
#browser.get('https://www.totaltraininfo.com/u.php')
#browser.get('https://www.totaltraininfo.com/v.php')
#browser.get('https://www.totaltraininfo.com/v.php?page=1')
#browser.get('https://www.totaltraininfo.com/w.php')
#browser.get('https://www.totaltraininfo.com/y.php')
browser.get('https://www.totaltraininfo.com/z.php')
browser.maximize_window()
for i in range(200):
    try:
        i1 = browser.find_element(By.XPATH, f"(//p/a)[{i+1}]")
        l1.append(i1.text)
    except:
        l1.append('NA')

print(l1)
df['Name'] = l1
#df.to_excel('a1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('a2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('a3.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('b1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('b2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('b3.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('b4.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('b5.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('b6.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('c1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('c2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('d1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('d2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('d3.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('e1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('f1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('g1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('g2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('g3.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('h1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('h2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('i1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('j1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('j2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('k1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('k2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('k3.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('k4.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('k5.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('k6.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('l1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('l2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('m1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('m2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('m3.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('m4.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('m5.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('n1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('n2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('n3.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('o1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('p1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('p2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('p3.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('q1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('r1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('r2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('s1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('s2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('s3.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('s4.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('s5.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('t1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('t2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('t3.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('u1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('v1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('v2.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('w1.xlsx', sheet_name='Sheet1', index = False)
#df.to_excel('y1.xlsx', sheet_name='Sheet1', index = False)
df.to_excel('z1.xlsx', sheet_name='Sheet1', index = False)
sleep(5)
browser.quit()